### ISSUE TITLE
Can't import BlocklyMethods

### ISSUE THREAD

**Issue by dlech** [OpenRoberta/robertalab-ev3dev#6]
#5 gets me farther than I was, but now I am getting an error when trying to run a program. I presume this error is in the code that is sent from the lab.open-roberta.org server.

```
Dec 28 21:29:59 ev3dev openrobertalab[1261]: INFO:roberta.lab:status changed: executing
Dec 28 21:30:00 ev3dev openrobertalab[1261]: INFO:roberta.lab:code downloaded to: /home/robot/NEPOprog.py
Dec 28 21:30:00 ev3dev openrobertalab[1261]: ERROR:roberta.lab:Ooops:
Dec 28 21:30:00 ev3dev openrobertalab[1261]: Traceback (most recent call last):
Dec 28 21:30:00 ev3dev openrobertalab[1261]: File "/usr/lib/python2.7/dist-packages/roberta/lab.py", line 237, in run
Dec 28 21:30:00 ev3dev openrobertalab[1261]: exec(code, globals(), globals())
Dec 28 21:30:00 ev3dev openrobertalab[1261]: File "/home/robot/NEPOprog.py", line 4, in <module>
Dec 28 21:30:00 ev3dev openrobertalab[1261]: from roberta.ev3 import Hal,BlocklyMethods
Dec 28 21:30:00 ev3dev openrobertalab[1261]: ImportError: cannot import name BlocklyMethods
Dec 28 21:30:00 ev3dev openrobertalab[1261]: INFO:roberta.lab:status changed: registered
```

It looks like BlocklyMethods may have moved? I think it should be `from roberta import BlocklyMethods` as a separate line.

**Comment by ensonic** [comment]
You are right. I'll figure something that is backwards compat.
